version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./backend/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: backend/.
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/code
    container_name: api
    restart: on-failure
    depends_on:
      - db
  frontend:
    build: frontend/.
    stdin_open: true
    container_name: ui
    links:
      - "web:api"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/app
      - /src/node_modules
