# Generated by Django 3.2.5 on 2021-07-31 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_booking', '0003_alter_appointment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SCHEDULED', 'scheduled'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled')], default='SCHEDULED', max_length=20)),
                ('created', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment_booking.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment_booking.patient')),
            ],
        ),
    ]
